project:
  type: website

website:
  title: "Mulimbika Makina"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    center: "Â© 2026 Mulimbika Makina"

format:
  html:
    theme: default
    toc: false
    css: styles.css
    include-after-body: background.html


# project:
#   type: website

# website:
#   title: "Mulimbika Makina"
#   navbar:
#     right:
#       - text: "Home"
#         href: index.qmd
#       - text: "Resume"
#         href: resume.qmd
#       - text: "Projects"
#         href: projects.qmd
#       - text: "Contact"
#         href: contact.qmd

# format:
#   html:
#     theme: default
#     page-layout: full

